//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartBeat.Logic.Email.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeartBeat.Logic.Email.Resources.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///        &lt;/table&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string MailEnd {
            get {
                return ResourceManager.GetString("MailEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///        &lt;title&gt;Your Message Subject or Title&lt;/title&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailStart {
            get {
                return ResourceManager.GetString("MailStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					&lt;/table&gt;		.
        /// </summary>
        internal static string StatusesEnd {
            get {
                return ResourceManager.GetString("StatusesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					&lt;table class=&quot;statustable&quot;&gt;.
        /// </summary>
        internal static string StatusesStart {
            get {
                return ResourceManager.GetString("StatusesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 						&lt;tr class=&quot;{0}&quot;&gt;
        ///							&lt;td class=&quot;statuscell&quot;&gt;{1}&lt;/td&gt;
        ///						&lt;/tr&gt;
        ///						&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string StatusFormatter {
            get {
                return ResourceManager.GetString("StatusFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					&lt;table class=&quot;statustable&quot;&gt;
        ///						&lt;tr&gt;
        ///							&lt;td colspan=&quot;2&quot; class=&quot;title&quot;&gt;Heart Beat Monitor Report&lt;/td&gt;
        ///						&lt;/tr&gt;
        ///						&lt;tr&gt;
        ///							&lt;td class=&quot;summarydescription&quot;&gt;Server&lt;/td&gt;
        ///							&lt;td class=&quot;summaryvalue&quot;&gt;{0}&lt;/td&gt;
        ///						&lt;/tr&gt;
        ///						&lt;tr&gt;
        ///							&lt;td class=&quot;summarydescription&quot;&gt;Report Time&lt;/td&gt;
        ///							&lt;td class=&quot;summaryvalue&quot;&gt;{1:yyyy-MM-dd HH:mm:ss}&lt;/td&gt;
        ///						&lt;/tr&gt;
        ///						&lt;tr&gt;
        ///							&lt;td class=&quot;summarydescription&quot;&gt;Total Tests Configured&lt;/td&gt;
        ///							&lt;td class=&quot;summaryvalue&quot;&gt;{2}&lt;/td&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SummaryFormatter {
            get {
                return ResourceManager.GetString("SummaryFormatter", resourceCulture);
            }
        }
    }
}
